--- 
title: "Physical activity calculator manual"
author: 
- Manuel A. Bolivar (ma.bolivar643@uniandes.edu.co)
- Olga Lucia Sarmiento (osarmien@uniandes.edu.co)
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a manual for processing children accelerometry data based on .agd files from ActiGraph."
---

# Introduction {#intro}

This code computes minutes of physical activity (PA) intensity (sedentary, light, moderate and vigorous) using  evidence-based cut points for accelerometry data (ActiGraph). The implemented procedure follows the protocol proposed by ISCOLE as treatment of accelerometry data for children. As an output for each participant, it provides: 1) Number of valid days of use; 2) Total wear time in minutes; 3) Average minutes and counts of each physical activity intensity level between days. It also calculates minutes and counts of each PA intensity level for midweek and weekend.

Results are exported to a CSV file.

## Table of contents
1. R and RStudio (Chapter \@ref(RnRstudio))
2. Setting everything up (Chapter \@ref(setup))
3. How to use this code? (Chapter \@ref(howto))
4. Results (Chapter \@ref(output))
5. Additional resources (Chapter \@ref(addresources))

